package lazi.model.customer;
// Generated Mar 23, 2017 3:00:59 PM by Hibernate Tools 3.6.0

import inet.util.string.StringUtil;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * KhKhachHangTtinh generated by hbm2java
 */
@Entity
@Table(name = "KH_KHACH_HANG_TTINH")
public class KhKhachHangTtinh implements java.io.Serializable, Comparable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "KH_KHACH_HANG_TTINH_GEN")
    @SequenceGenerator(name = "KH_KHACH_HANG_TTINH_GEN", sequenceName = "KH_KHACH_HANG_TTINH_SEQ")
    @Column(name = "ID")
    private long id;
    @Column(name = "ID_KHANG")
    private long idKhang;
    @Column(name = "NGAY_APDUNG_CKHAU")
    private Date ngayApdungCkhau;
    @Column(name = "SO_CMND")
    private String soCmnd;
    @Column(name = "GIOI_TINH")
    private String gioiTinh;
    @Column(name = "NGAY_SINH")
    private Date ngaySinh;
    @Column(name = "NGAY_THAM_GIA")
    private Date ngayThamGia;
    @Column(name = "NGAY_HET_HLUC")
    private Date ngayHetHluc;
    @Column(name = "DDAN_HINH_ANH")
    private String ddanHinhAnh;
    @Column(name = "DIA_CHI")
    private String diaChi;
    @Column(name = "MA_TINHTP")
    private String maTinhtp;
    @Column(name = "MA_QUAN")
    private String maQuan;
    @Column(name = "MA_PHUONG")
    private String maPhuong;
    @Column(name = "EMAIL")
    private String email;
    @Column(name = "MA_DVI_QLY")
    private String maDviQly;
    @Column(name = "MA_DVI_TAO")
    private String maDviTao;
    @Column(name = "NGAY_NHAP")
    private Date ngayNhap;
    @Column(name = "NGUOI_NHAP")
    private String nguoiNhap;
    @Column(name = "NGAY_CNHAT")
    private Date ngayCnhat;
    @Column(name = "NGUOI_CNHAT")
    private String nguoiCnhat;
    @Column(name = "GHI_CHU")
    private String ghiChu;

    public KhKhachHangTtinh() {
    }

    @Override
    public int compareTo(Object object) {
        if(object == null) return -1;
        KhKhachHangTtinh e = (KhKhachHangTtinh) object;
        if(e.getId() > this.getId()) return 1;
        else if(e.getId() < this.getId()) return -1;
        
        if(e.getIdKhang() > this.getIdKhang()) return 1;
        else if(e.getIdKhang() < this.getIdKhang()) return -1;
        
        
        if(!StringUtil.isNullOrEmpty(e.getSoCmnd())) {
            if(e.getSoCmnd().compareTo(this.getSoCmnd()) > 0) return 1;
            else if(e.getSoCmnd().compareTo(this.getSoCmnd()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getSoCmnd())) {
            return -1;
        }
        
        if(e.getNgayApdungCkhau() != null) {
            if(e.getNgayApdungCkhau().compareTo(this.getNgayApdungCkhau()) > 0) return 1;
            else if(e.getNgayApdungCkhau().compareTo(this.getNgayApdungCkhau()) < 0) return -1;
        } else if(this.getNgayApdungCkhau() != null) {
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getGioiTinh())) {
            if(e.getGioiTinh().compareTo(this.getGioiTinh()) > 0) return 1;
            else if(e.getGioiTinh().compareTo(this.getGioiTinh()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getGioiTinh())) {
            return -1;
        }
        
        if(e.getNgaySinh()!= null) {
            if(e.getNgaySinh().compareTo(this.getNgaySinh()) > 0) return 1;
            else if(e.getNgaySinh().compareTo(this.getNgaySinh()) < 0) return -1;
        } else if(this.getNgaySinh() != null) {
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getDiaChi())) {
            if(e.getDiaChi().compareTo(this.getDiaChi()) > 0) return 1;
            else if(e.getDiaChi().compareTo(this.getDiaChi()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getDiaChi())){
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getMaTinhtp())) {
            if(e.getMaTinhtp().compareTo(this.getMaTinhtp()) > 0) return 1;
            else if(e.getMaTinhtp().compareTo(this.getMaTinhtp()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getMaTinhtp())){
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getMaQuan())) {
            if(e.getMaQuan().compareTo(this.getMaQuan()) > 0) return 1;
            else if(e.getMaQuan().compareTo(this.getMaQuan()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getMaQuan())){
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getMaPhuong())) {
            if(e.getMaPhuong().compareTo(this.getMaPhuong()) > 0) return 1;
            else if(e.getMaPhuong().compareTo(this.getMaPhuong()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getMaPhuong())){
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getEmail())) {
            if(e.getEmail().compareTo(this.getEmail()) > 0) return 1;
            else if(e.getEmail().compareTo(this.getEmail()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getEmail())){
            return -1;
        }
        
        return 0;
    }
    
    public KhKhachHangTtinh(long id, long idKhang, Date ngayThamGia, String maDviQly, String maDviTao, Date ngayNhap, String nguoiNhap) {
        this.id = id;
        this.idKhang = idKhang;
        this.ngayThamGia = ngayThamGia;
        this.maDviQly = maDviQly;
        this.maDviTao = maDviTao;
        this.ngayNhap = ngayNhap;
        this.nguoiNhap = nguoiNhap;
    }

    public KhKhachHangTtinh(long id, long idKhang, Date ngayApdungCkhau, String soCmnd, String gioiTinh, Date ngaySinh, Date ngayThamGia, Date ngayHetHluc, String ddanHinhAnh, String diaChi, String maTinhtp, String maQuan, String maPhuong, String email, String maDviQly, String maDviTao, Date ngayNhap, String nguoiNhap, Date ngayCnhat, String nguoiCnhat) {
        this.id = id;
        this.idKhang = idKhang;
        this.ngayApdungCkhau = ngayApdungCkhau;
        this.soCmnd = soCmnd;
        this.gioiTinh = gioiTinh;
        this.ngaySinh = ngaySinh;
        this.ngayThamGia = ngayThamGia;
        this.ngayHetHluc = ngayHetHluc;
        this.ddanHinhAnh = ddanHinhAnh;
        this.diaChi = diaChi;
        this.maTinhtp = maTinhtp;
        this.maQuan = maQuan;
        this.maPhuong = maPhuong;
        this.email = email;
        this.maDviQly = maDviQly;
        this.maDviTao = maDviTao;
        this.ngayNhap = ngayNhap;
        this.nguoiNhap = nguoiNhap;
        this.ngayCnhat = ngayCnhat;
        this.nguoiCnhat = nguoiCnhat;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getIdKhang() {
        return this.idKhang;
    }

    public void setIdKhang(long idKhang) {
        this.idKhang = idKhang;
    }

    public Date getNgayApdungCkhau() {
        return this.ngayApdungCkhau;
    }

    public void setNgayApdungCkhau(Date ngayApdungCkhau) {
        this.ngayApdungCkhau = ngayApdungCkhau;
    }

    public String getSoCmnd() {
        return soCmnd;
    }

    public void setSoCmnd(String soCmnd) {
        this.soCmnd = soCmnd;
    }

    public String getGioiTinh() {
        return this.gioiTinh;
    }

    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    public Date getNgaySinh() {
        return this.ngaySinh;
    }

    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    public Date getNgayThamGia() {
        return this.ngayThamGia;
    }

    public void setNgayThamGia(Date ngayThamGia) {
        this.ngayThamGia = ngayThamGia;
    }

    public Date getNgayHetHluc() {
        return this.ngayHetHluc;
    }

    public void setNgayHetHluc(Date ngayHetHluc) {
        this.ngayHetHluc = ngayHetHluc;
    }

    public String getDdanHinhAnh() {
        return this.ddanHinhAnh;
    }

    public void setDdanHinhAnh(String ddanHinhAnh) {
        this.ddanHinhAnh = ddanHinhAnh;
    }

    public String getDiaChi() {
        return this.diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getMaTinhtp() {
        return this.maTinhtp;
    }

    public void setMaTinhtp(String maTinhtp) {
        this.maTinhtp = maTinhtp;
    }

    public String getMaQuan() {
        return this.maQuan;
    }

    public void setMaQuan(String maQuan) {
        this.maQuan = maQuan;
    }

    public String getMaPhuong() {
        return this.maPhuong;
    }

    public void setMaPhuong(String maPhuong) {
        this.maPhuong = maPhuong;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getMaDviQly() {
        return this.maDviQly;
    }

    public void setMaDviQly(String maDviQly) {
        this.maDviQly = maDviQly;
    }

    public String getMaDviTao() {
        return this.maDviTao;
    }

    public void setMaDviTao(String maDviTao) {
        this.maDviTao = maDviTao;
    }

    public Date getNgayNhap() {
        return this.ngayNhap;
    }

    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }

    public String getNguoiNhap() {
        return this.nguoiNhap;
    }

    public void setNguoiNhap(String nguoiNhap) {
        this.nguoiNhap = nguoiNhap;
    }

    public Date getNgayCnhat() {
        return this.ngayCnhat;
    }

    public void setNgayCnhat(Date ngayCnhat) {
        this.ngayCnhat = ngayCnhat;
    }

    public String getNguoiCnhat() {
        return this.nguoiCnhat;
    }

    public void setNguoiCnhat(String nguoiCnhat) {
        this.nguoiCnhat = nguoiCnhat;
    }

    public String getGhiChu() {
        return ghiChu;
    }

    public void setGhiChu(String ghiChu) {
        this.ghiChu = ghiChu;
    }

    
}
