package lazi.model.customer;
// Generated Mar 23, 2017 3:00:59 PM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * KhKhachHangLsu generated by hbm2java
 */
@Entity
@Table(name = "KH_KHACH_HANG_LSU")
public class KhKhachHangLsu implements java.io.Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "KH_KHACH_HANG_LSU_GEN")
    @SequenceGenerator(name = "KH_KHACH_HANG_LSU_GEN", sequenceName = "KH_KHACH_HANG_LSU_SEQ")
    @Column(name = "ID")
    private long id;
    @Column(name = "ID_KHANG")
    private long idKhang;
    @Column(name = "ID_KHANG_LOAI")
    private long idKhangLoai;
    @Column(name = "MA_KHANG_LOAI")
    private String maKhangLoai;
    @Column(name = "MA_KHANG")
    private String maKhang;
    @Column(name = "TEN_KHANG")
    private String tenKhang;
    @Column(name = "SO_CMND")
    private String soCmnd;
    @Column(name = "APDUNG_CKHAU")
    private int apdungCkhau;
    @Column(name = "NGAY_APDUNG_CKHAU")
    private Date ngayApdungCkhau;
    @Column(name = "GIOI_TINH")
    private String gioiTinh;
    @Column(name = "NGAY_SINH")
    private Date ngaySinh;
    @Column(name = "NGAY_THAM_GIA")
    private Date ngayThamGia;
    @Column(name = "NGAY_HET_HLUC")
    private Date ngayHetHluc;
    @Column(name = "DDAN_HINH_ANH")
    private String ddanHinhAnh;
    @Column(name = "DIA_CHI")
    private String diaChi;
    @Column(name = "MA_TINHTP")
    private String maTinhtp;
    @Column(name = "MA_QUAN")
    private String maQuan;
    @Column(name = "MA_PHUONG")
    private String maPhuong;
    @Column(name = "SO_DTHOAI")
    private String soDthoai;
    @Column(name = "EMAIL")
    private String email;
    @Column(name = "TTHAI_BGHI")
    private String tthaiBghi;
    @Column(name = "TTHAI_NVU")
    private String tthaiNvu;
    @Column(name = "MA_DVI_QLY")
    private String maDviQly;
    @Column(name = "MA_DVI_TAO")
    private String maDviTao;
    @Column(name = "NGAY_CNHAT")
    private Date ngayCnhat;
    @Column(name = "NGUOI_CNHAT")
    private String nguoiCnhat;

    public KhKhachHangLsu() {
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getIdKhang() {
        return idKhang;
    }

    public void setIdKhang(long idKhang) {
        this.idKhang = idKhang;
    }

    public long getIdKhangLoai() {
        return idKhangLoai;
    }

    public void setIdKhangLoai(long idKhangLoai) {
        this.idKhangLoai = idKhangLoai;
    }

    public String getMaKhangLoai() {
        return this.maKhangLoai;
    }

    public void setMaKhangLoai(String maKhangLoai) {
        this.maKhangLoai = maKhangLoai;
    }

    public String getMaKhang() {
        return this.maKhang;
    }

    public void setMaKhang(String maKhang) {
        this.maKhang = maKhang;
    }

    public String getTenKhang() {
        return this.tenKhang;
    }

    public void setTenKhang(String tenKhang) {
        this.tenKhang = tenKhang;
    }

    public String getSoCmnd() {
        return this.soCmnd;
    }

    public void setSoCmnd(String soCmnd) {
        this.soCmnd = soCmnd;
    }

    public int getApdungCkhau() {
        return this.apdungCkhau;
    }

    public void setApdungCkhau(int apdungCkhau) {
        this.apdungCkhau = apdungCkhau;
    }

    public Date getNgayApdungCkhau() {
        return this.ngayApdungCkhau;
    }

    public void setNgayApdungCkhau(Date ngayApdungCkhau) {
        this.ngayApdungCkhau = ngayApdungCkhau;
    }

    public String getGioiTinh() {
        return this.gioiTinh;
    }

    public void setGioiTinh(String gioiTinh) {
        this.gioiTinh = gioiTinh;
    }

    public Date getNgaySinh() {
        return this.ngaySinh;
    }

    public void setNgaySinh(Date ngaySinh) {
        this.ngaySinh = ngaySinh;
    }

    public Date getNgayThamGia() {
        return this.ngayThamGia;
    }

    public void setNgayThamGia(Date ngayThamGia) {
        this.ngayThamGia = ngayThamGia;
    }

    public Date getNgayHetHluc() {
        return this.ngayHetHluc;
    }

    public void setNgayHetHluc(Date ngayHetHluc) {
        this.ngayHetHluc = ngayHetHluc;
    }

    public String getDdanHinhAnh() {
        return this.ddanHinhAnh;
    }

    public void setDdanHinhAnh(String ddanHinhAnh) {
        this.ddanHinhAnh = ddanHinhAnh;
    }

    public String getDiaChi() {
        return this.diaChi;
    }

    public void setDiaChi(String diaChi) {
        this.diaChi = diaChi;
    }

    public String getMaTinhtp() {
        return this.maTinhtp;
    }

    public void setMaTinhtp(String maTinhtp) {
        this.maTinhtp = maTinhtp;
    }

    public String getMaQuan() {
        return this.maQuan;
    }

    public void setMaQuan(String maQuan) {
        this.maQuan = maQuan;
    }

    public String getMaPhuong() {
        return this.maPhuong;
    }

    public void setMaPhuong(String maPhuong) {
        this.maPhuong = maPhuong;
    }

    public String getSoDthoai() {
        return this.soDthoai;
    }

    public void setSoDthoai(String soDthoai) {
        this.soDthoai = soDthoai;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getTthaiBghi() {
        return this.tthaiBghi;
    }

    public void setTthaiBghi(String tthaiBghi) {
        this.tthaiBghi = tthaiBghi;
    }

    public String getTthaiNvu() {
        return this.tthaiNvu;
    }

    public void setTthaiNvu(String tthaiNvu) {
        this.tthaiNvu = tthaiNvu;
    }

    public String getMaDviQly() {
        return this.maDviQly;
    }

    public void setMaDviQly(String maDviQly) {
        this.maDviQly = maDviQly;
    }

    public String getMaDviTao() {
        return this.maDviTao;
    }

    public void setMaDviTao(String maDviTao) {
        this.maDviTao = maDviTao;
    }

    public Date getNgayCnhat() {
        return this.ngayCnhat;
    }

    public void setNgayCnhat(Date ngayCnhat) {
        this.ngayCnhat = ngayCnhat;
    }

    public String getNguoiCnhat() {
        return this.nguoiCnhat;
    }

    public void setNguoiCnhat(String nguoiCnhat) {
        this.nguoiCnhat = nguoiCnhat;
    }

}
