package lazi.model.customer;
// Generated Mar 23, 2017 3:00:59 PM by Hibernate Tools 3.6.0

import inet.util.string.StringUtil;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Transient;

/**
 * KhKhachHang generated by hbm2java
 */
@Entity
@Table(name = "KH_KHACH_HANG")
public class KhKhachHang implements java.io.Serializable, Comparable {

    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @GeneratedValue(strategy = GenerationType.AUTO, generator = "KH_KHACH_HANG_GEN")
    @SequenceGenerator(name = "KH_KHACH_HANG_GEN", sequenceName = "KH_KHACH_HANG_SEQ")
    @Column(name = "ID")
    private long id;
    @Column(name = "ID_KHANG_LOAI")
    private long idKhangLoai;
    @Column(name = "MA_KHANG_LOAI")
    private String maKhangLoai;
    @Column(name = "MA_KHANG")
    private String maKhang;
    @Column(name = "TEN_KHANG")
    private String tenKhang;
    @Column(name = "ID_THE_KHACHHANG")
    private long idTheKhachhang;
    @Column(name = "SO_DTHOAI")
    private String soDthoai;
    @Column(name = "TTHAI_BGHI")
    private String tthaiBghi;
    @Column(name = "TTHAI_NVU")
    private String tthaiNvu;
    @Column(name = "MA_DVI_QLY")
    private String maDviQly;
    @Column(name = "NGAY_NHAP")
    private Date ngayNhap;
    @Column(name = "NGUOI_NHAP")
    private String nguoiNhap;
    @Column(name = "NGAY_CNHAT")
    private Date ngayCnhat;
    @Column(name = "NGUOI_CNHAT")
    private String nguoiCnhat;
    @Column(name = "APDUNG_CKHAU")
    private int apdungCkhau;
    @Column(name = "MA_THCHIEU")
    private String maThamChieu;
    @Column(name = "DOANH_SO")
    private double doanhSo;
    
    @Transient
    private KhKhachHangTtinh khKhachHangTtinh;
    
    public KhKhachHang() {
    }

    @Override
    public int compareTo(Object object) {
        if(object == null) return -1;
        KhKhachHang e = (KhKhachHang) object;
        if(e.getIdKhangLoai() > this.getIdKhangLoai()) return 1;
        else if(e.getIdKhangLoai() < this.getIdKhangLoai()) return -1;
        
        if(!StringUtil.isNullOrEmpty(e.getTenKhang())) {
            if(e.getTenKhang().compareTo(this.getTenKhang()) > 0) return 1;
            else if(e.getTenKhang().compareTo(this.getTenKhang()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getTenKhang())) {
            return -1;
        }
        
        if(e.getIdTheKhachhang()> this.getIdTheKhachhang()) return 1;
        else if(e.getIdTheKhachhang() < this.getIdTheKhachhang()) return -1;
        
        if(e.getApdungCkhau() > this.getApdungCkhau()) return 1;
        else if(e.getApdungCkhau() < this.getApdungCkhau()) return -1;
        
        if(!StringUtil.isNullOrEmpty(e.getSoDthoai())) {
            if(e.getSoDthoai().compareTo(this.getSoDthoai()) > 0) return 1;
            else if(e.getSoDthoai().compareTo(this.getSoDthoai()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getSoDthoai())) {
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getTthaiBghi())) {
            if(e.getTthaiBghi().compareTo(this.getTthaiBghi()) > 0) return 1;
            else if(e.getTthaiBghi().compareTo(this.getTthaiBghi()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getTthaiBghi())){
            return -1;
        }
        
        if(!StringUtil.isNullOrEmpty(e.getTthaiNvu())) {
            if(e.getTthaiNvu().compareTo(this.getTthaiNvu()) > 0) return 1;
            else if(e.getTthaiNvu().compareTo(this.getTthaiNvu()) < 0) return -1;
        } else if(!StringUtil.isNullOrEmpty(this.getTthaiNvu())){
            return -1;
        }
        
        return 0;
    }
    
    public static void main(String[] args) {
    }
    
    public KhKhachHang(long id, long idKhangLoai, String maKhangLoai, String maKhang, String tenKhang, String tthaiBghi, String tthaiNvu, String maDviQly, Date ngayNhap, String nguoiNhap) {
        this.id = id;
        this.idKhangLoai = idKhangLoai;
        this.maKhangLoai = maKhangLoai;
        this.maKhang = maKhang;
        this.tenKhang = tenKhang;
        this.tthaiBghi = tthaiBghi;
        this.tthaiNvu = tthaiNvu;
        this.maDviQly = maDviQly;
        this.ngayNhap = ngayNhap;
        this.nguoiNhap = nguoiNhap;
    }

    public KhKhachHang(long id, long idKhangLoai, String maKhangLoai, String maKhang, String tenKhang, String soCmnd, String soDthoai, String tthaiBghi, String tthaiNvu, String maDviQly, Date ngayNhap, String nguoiNhap, Date ngayCnhat, String nguoiCnhat) {
        this.id = id;
        this.idKhangLoai = idKhangLoai;
        this.maKhangLoai = maKhangLoai;
        this.maKhang = maKhang;
        this.tenKhang = tenKhang;
        this.idTheKhachhang = idTheKhachhang;
        this.soDthoai = soDthoai;
        this.tthaiBghi = tthaiBghi;
        this.tthaiNvu = tthaiNvu;
        this.maDviQly = maDviQly;
        this.ngayNhap = ngayNhap;
        this.nguoiNhap = nguoiNhap;
        this.ngayCnhat = ngayCnhat;
        this.nguoiCnhat = nguoiCnhat;
    }

    public long getId() {
        return this.id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public long getIdKhangLoai() {
        return idKhangLoai;
    }

    public void setIdKhangLoai(long idKhangLoai) {
        this.idKhangLoai = idKhangLoai;
    }

    public String getMaKhangLoai() {
        return this.maKhangLoai;
    }

    public void setMaKhangLoai(String maKhangLoai) {
        this.maKhangLoai = maKhangLoai;
    }

    public String getMaKhang() {
        return this.maKhang;
    }

    public void setMaKhang(String maKhang) {
        this.maKhang = maKhang;
    }

    public String getTenKhang() {
        return this.tenKhang;
    }

    public void setTenKhang(String tenKhang) {
        this.tenKhang = tenKhang;
    }

    public long getIdTheKhachhang() {
        return idTheKhachhang;
    }

    public void setIdTheKhachhang(long idTheKhachhang) {
        this.idTheKhachhang = idTheKhachhang;
    }

    public String getSoDthoai() {
        return this.soDthoai;
    }

    public void setSoDthoai(String soDthoai) {
        this.soDthoai = soDthoai;
    }

    public String getTthaiBghi() {
        return this.tthaiBghi;
    }

    public void setTthaiBghi(String tthaiBghi) {
        this.tthaiBghi = tthaiBghi;
    }

    public String getTthaiNvu() {
        return this.tthaiNvu;
    }

    public void setTthaiNvu(String tthaiNvu) {
        this.tthaiNvu = tthaiNvu;
    }

    public String getMaDviQly() {
        return this.maDviQly;
    }

    public void setMaDviQly(String maDviQly) {
        this.maDviQly = maDviQly;
    }

    public Date getNgayNhap() {
        return this.ngayNhap;
    }

    public void setNgayNhap(Date ngayNhap) {
        this.ngayNhap = ngayNhap;
    }

    public String getNguoiNhap() {
        return this.nguoiNhap;
    }

    public void setNguoiNhap(String nguoiNhap) {
        this.nguoiNhap = nguoiNhap;
    }

    public Date getNgayCnhat() {
        return this.ngayCnhat;
    }

    public void setNgayCnhat(Date ngayCnhat) {
        this.ngayCnhat = ngayCnhat;
    }

    public String getNguoiCnhat() {
        return this.nguoiCnhat;
    }

    public void setNguoiCnhat(String nguoiCnhat) {
        this.nguoiCnhat = nguoiCnhat;
    }

    public int getApdungCkhau() {
        return apdungCkhau;
    }

    public void setApdungCkhau(int apdungCkhau) {
        this.apdungCkhau = apdungCkhau;
    }

    public KhKhachHangTtinh getKhKhachHangTtinh() {
        return khKhachHangTtinh;
    }

    public void setKhKhachHangTtinh(KhKhachHangTtinh khKhachHangTtinh) {
        this.khKhachHangTtinh = khKhachHangTtinh;
    }

    public String getMaThamChieu() {
        return maThamChieu;
    }

    public void setMaThamChieu(String maThamChieu) {
        this.maThamChieu = maThamChieu;
    }

    public double getDoanhSo() {
        return doanhSo;
    }

    public void setDoanhSo(double doanhSo) {
        this.doanhSo = doanhSo;
    }
    

}
